-- ADMINISTRADORES (Todos tienen como contraseña "admin") --
INSERT INTO user(nickname,password,enabled,first_name,last_name,email,creation_date,type,birth_date,avatar) VALUES ('admin1','$2a$10$DXvKFs64uY6HJKVy.clI3uaJeWNvBtB.r62FrZ1x.gTcTc2jGxb5y','TRUE','Admin FN','Admin LN','admin1@sevenislands.com','2022-10-29','admin','2022-10-29','adminAvatar.png');
INSERT INTO user(nickname,password,enabled,first_name,last_name,email,creation_date,type,birth_date,avatar) VALUES ('albperleo','$2a$10$DXvKFs64uY6HJKVy.clI3uaJeWNvBtB.r62FrZ1x.gTcTc2jGxb5y','TRUE','Alberto','Perea Leon','albperleo@sevenislands.com','2022-10-29','admin','2022-10-29','adminAvatar.png');
INSERT INTO user(nickname,password,enabled,first_name,last_name,email,creation_date,type,birth_date,avatar) VALUES ('javnunrui','$2a$10$DXvKFs64uY6HJKVy.clI3uaJeWNvBtB.r62FrZ1x.gTcTc2jGxb5y','TRUE','Javier','Nunes Ruiz','javnunrui@sevenislands.com','2022-10-29','admin','2022-10-29','adminAvatar.png');
INSERT INTO user(nickname,password,enabled,first_name,last_name,email,creation_date,type,birth_date,avatar) VALUES ('marvicmar','$2a$10$DXvKFs64uY6HJKVy.clI3uaJeWNvBtB.r62FrZ1x.gTcTc2jGxb5y','TRUE','Maria','Vico Martin','marvicmar@sevenislands.com','2022-10-29','admin','2022-10-29','adminAvatar.png');
INSERT INTO user(nickname,password,enabled,first_name,last_name,email,creation_date,type,birth_date,avatar) VALUES ('juaramlop2','$2a$10$DXvKFs64uY6HJKVy.clI3uaJeWNvBtB.r62FrZ1x.gTcTc2jGxb5y','TRUE','Juan Carlos','Ramirez Lopez','juaramlop2@sevenislands.com','2022-10-29','admin','2022-10-29','adminAvatar.png');
INSERT INTO user(nickname,password,enabled,first_name,last_name,email,creation_date,type,birth_date,avatar) VALUES ('alepervaz','$2a$10$DXvKFs64uY6HJKVy.clI3uaJeWNvBtB.r62FrZ1x.gTcTc2jGxb5y','TRUE','Alejandro','Perez Vazquez','alepervaz@sevenislands.com','2022-10-29','admin','2022-10-29','adminAvatar.png');

-- JUGADORES (Todos tienen como contraseña "player") --
INSERT INTO user(nickname,password,enabled,first_name,last_name,email,creation_date,type,birth_date,avatar) VALUES ('player1','$2a$10$Yurjw7YseLzZq/JOixdY/eRmBrOIzHHNooczuuMwtC42R8vRoKVPC','TRUE','Player FN','Player LN','player1@sevenislands.com','2022-10-29','player','2022-10-29','playerAvatar.png');
INSERT INTO user(nickname,password,enabled,first_name,last_name,email,creation_date,type,birth_date,avatar) VALUES ('player2','$2a$10$Yurjw7YseLzZq/JOixdY/eRmBrOIzHHNooczuuMwtC42R8vRoKVPC','TRUE','Player FN','Player LN','player2@sevenislands.com','2022-10-29','player','2022-10-29','playerAvatar.png');
INSERT INTO user(nickname,password,enabled,first_name,last_name,email,creation_date,type,birth_date,avatar) VALUES ('player3','$2a$10$Yurjw7YseLzZq/JOixdY/eRmBrOIzHHNooczuuMwtC42R8vRoKVPC','TRUE','Player FN','Player LN','player3@sevenislands.com','2022-10-29','player','2022-10-29','playerAvatar.png');
INSERT INTO user(nickname,password,enabled,first_name,last_name,email,creation_date,type,birth_date,avatar) VALUES ('player4','$2a$10$Yurjw7YseLzZq/JOixdY/eRmBrOIzHHNooczuuMwtC42R8vRoKVPC','TRUE','Player FN','Player LN','player4@sevenislands.com','2022-10-29','player','2022-10-29','playerAvatar.png');
INSERT INTO user(nickname,password,enabled,first_name,last_name,email,creation_date,type,birth_date,avatar) VALUES ('player5','$2a$10$Yurjw7YseLzZq/JOixdY/eRmBrOIzHHNooczuuMwtC42R8vRoKVPC','TRUE','Player FN','Player LN','player5@sevenislands.com','2022-10-29','player','2022-10-29','playerAvatar.png');

-- LOBBY --
INSERT INTO lobby(active,code) VALUES('FALSE','ZgC[pLc>');

-- LOBBY JUGADORES -- 
INSERT INTO lobby_users(lobby_id,users_id) VALUES (1,7);
INSERT INTO lobby_users(lobby_id,users_id) VALUES (1,8);
INSERT INTO lobby_users(lobby_id,users_id) VALUES (1,9);
INSERT INTO lobby_users(lobby_id,users_id) VALUES (1,10);

-- JUEGOS -- 
INSERT INTO game(active,creation_date,ending_date,tie_break,lobby_id,winner_id) VALUES('FALSE','2023-01-06 12:59:40.241642','2023-01-06 13:03:28.611833','FALSE',1,8);


-- RONDAS --
INSERT INTO round(game_id) VALUES(1);
INSERT INTO round(game_id) VALUES(1);
INSERT INTO round(game_id) VALUES(1);
INSERT INTO round(game_id) VALUES(1);
INSERT INTO round(game_id) VALUES(1);
INSERT INTO round(game_id) VALUES(1);
INSERT INTO round(game_id) VALUES(1);
INSERT INTO round(game_id) VALUES(1);
INSERT INTO round(game_id) VALUES(1);
INSERT INTO round(game_id) VALUES(1);
INSERT INTO round(game_id) VALUES(1);
INSERT INTO round(game_id) VALUES(1);
INSERT INTO round(game_id) VALUES(1);
INSERT INTO round(game_id) VALUES(1);
INSERT INTO round(game_id) VALUES(1);

-- TURNOS -- 
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(null,'2023-01-06 12:59:42.062364',1,7);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(null,'2023-01-06 12:59:42.063363',1,8);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(null,'2023-01-06 12:59:42.065364',1,9);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(null,'2023-01-06 12:59:42.066365',1,10);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(5,'2023-01-06 12:59:42.079365',2,7);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(4,'2023-01-06 12:59:50.323424',2,8);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(3,'2023-01-06 12:59:54.213482',2,9);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(3,'2023-01-06 12:59:57.207096',2,10);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(1,'2023-01-06 13:00:00.046335',3,7);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(2,'2023-01-06 13:00:05.139802',3,8);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(2,'2023-01-06 13:00:07.79648',3,9);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(6,'2023-01-06 13:00:10.869161',3,10);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(6,'2023-01-06 13:00:13.862484',4,7);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(3,'2023-01-06 13:00:18.072992',4,8);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(5,'2023-01-06 13:00:20.354533',4,9);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(5,'2023-01-06 13:00:24.049461',4,10);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(5,'2023-01-06 13:00:26.774032',5,7);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(4,'2023-01-06 13:00:29.831881',5,8);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(3,'2023-01-06 13:00:31.853782',5,9);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(2,'2023-01-06 13:00:34.721853',5,10);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(3,'2023-01-06 13:00:37.915812',6,7);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(3,'2023-01-06 13:00:43.722092',6,8);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(1,'2023-01-06 13:00:46.262734',6,9);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(4,'2023-01-06 13:00:49.978015',6,10);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(4,'2023-01-06 13:00:52.856024',7,7);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(4,'2023-01-06 13:00:56.935298',7,8);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(4,'2023-01-06 13:00:59.68276',7,9);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(6,'2023-01-06 13:01:02.9207',7,10);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(2,'2023-01-06 13:01:06.122596',8,7);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(1,'2023-01-06 13:01:12.121765',8,8);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(6,'2023-01-06 13:01:14.168787',8,9);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(5,'2023-01-06 13:01:16.599847',8,10);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(6,'2023-01-06 13:01:18.824844',9,7);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(6,'2023-01-06 13:01:22.890973',9,8);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(6,'2023-01-06 13:01:26.168576',9,9);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(4,'2023-01-06 13:01:28.904729',9,10);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(3,'2023-01-06 13:01:33.276541',10,7);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(6,'2023-01-06 13:01:36.79184',10,8);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(6,'2023-01-06 13:01:42.004718',10,9);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(5,'2023-01-06 13:01:45.380555',10,10);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(1,'2023-01-06 13:01:48.228669',11,7);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(3,'2023-01-06 13:01:51.605339',11,8);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(3,'2023-01-06 13:01:53.897245',11,9);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(4,'2023-01-06 13:01:58.31603',11,10);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(3,'2023-01-06 13:02:01.15373',12,7);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(4,'2023-01-06 13:02:03.817399',12,8);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(5,'2023-01-06 13:02:07.343122',12,9);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(3,'2023-01-06 13:02:10.801373',12,10);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(3,'2023-01-06 13:02:13.754543',13,7);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(6,'2023-01-06 13:02:17.587944',13,8);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(2,'2023-01-06 13:02:19.840936',13,9);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(5,'2023-01-06 13:02:23.497269',13,10);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(3,'2023-01-06 13:02:26.460901',14,7);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(4,'2023-01-06 13:02:31.507286',14,8);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(4,'2023-01-06 13:02:33.799739',14,9);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(4,'2023-01-06 13:02:52.573388',14,10);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(3,'2023-01-06 13:03:05.923151',15,7);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(4,'2023-01-06 13:03:19.608027',15,8);
INSERT INTO turn(dice, start_time,round_id,user_id) VALUES(null,'2023-01-06 13:03:28.596952',15,9);


-- CARTA --
INSERT INTO card(multiplicity,tipo,game_id) VALUES(0,'Collar',1);
INSERT INTO card(multiplicity,tipo,game_id) VALUES(0,'Doblon',1);
INSERT INTO card(multiplicity,tipo,game_id) VALUES(0,'Espada',1);
INSERT INTO card(multiplicity,tipo,game_id) VALUES(0,'Diamante',1);
INSERT INTO card(multiplicity,tipo,game_id) VALUES(0,'Rubi',1);
INSERT INTO card(multiplicity,tipo,game_id) VALUES(0,'Corona',1);
INSERT INTO card(multiplicity,tipo,game_id) VALUES(0,'Caliz',1);
INSERT INTO card(multiplicity,tipo,game_id) VALUES(0,'MapaTesoro',1);
INSERT INTO card(multiplicity,tipo,game_id) VALUES(0,'Revolver',1);
INSERT INTO card(multiplicity,tipo,game_id) VALUES(0,'BarrilRon',1);


-- ISLA --
INSERT INTO island(island_number, card_id, game_id) VALUES(0,2,1);
INSERT INTO island(island_number, card_id, game_id) VALUES(0,2,1);
INSERT INTO island(island_number, card_id, game_id) VALUES(0,9,1);
INSERT INTO island(island_number, card_id, game_id) VALUES(0,8,1);
INSERT INTO island(island_number, card_id, game_id) VALUES(0,7,1);
INSERT INTO island(island_number, card_id, game_id) VALUES(0,7,1);


-- TURNO_CARTA --
INSERT INTO turn_cards(turn_id,cards_id) VALUES(1,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(1,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(1,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(2,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(2,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(2,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(3,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(3,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(3,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(4,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(4,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(4,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(5,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(5,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(5,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(5,10);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(6,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(6,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(6,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(6,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(7,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(7,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(7,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(7,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(8,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(8,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(8,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(8,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(9,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(9,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(9,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(9,10);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(9,3);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(10,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(10,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(10,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(10,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(10,6);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(11,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(11,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(11,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(11,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(11,5);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(12,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(12,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(12,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(12,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(12,1);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(13,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(13,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(13,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(13,10);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(13,3);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(13,3);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(14,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(14,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(14,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(14,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(14,6);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(14,9);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(15,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(15,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(15,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(15,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(15,5);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(15,9);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(16,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(16,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(16,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(16,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(16,1);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(16,1);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(17,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(17,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(17,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(17,10);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(17,3);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(17,3);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(17,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(18,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(18,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(18,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(18,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(18,6);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(18,9);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(18,3);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(19,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(19,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(19,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(19,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(19,5);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(19,9);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(19,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(20,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(20,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(20,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(20,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(20,1);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(20,1);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(20,9);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(21,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(21,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(21,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(21,10);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(21,3);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(21,3);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(21,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(21,4);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(22,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(22,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(22,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(22,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(22,6);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(22,9);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(22,3);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(22,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(23,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(23,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(23,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(23,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(23,5);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(23,9);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(23,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(23,8);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(24,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(24,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(24,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(24,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(24,1);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(24,1);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(24,9);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(24,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(25,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(25,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(25,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(25,10);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(25,3);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(25,3);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(25,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(25,4);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(25,6);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(26,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(26,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(26,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(26,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(26,6);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(26,9);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(26,3);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(26,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(26,10);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(27,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(27,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(27,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(27,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(27,5);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(27,9);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(27,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(27,8);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(27,10);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(28,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(28,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(28,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(28,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(28,1);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(28,1);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(28,9);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(28,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(28,3);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(29,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(29,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(29,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(29,10);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(29,3);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(29,3);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(29,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(29,4);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(29,6);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(29,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(30,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(30,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(30,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(30,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(30,6);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(30,9);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(30,3);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(30,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(30,10);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(30,5);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(31,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(31,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(31,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(31,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(31,5);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(31,9);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(31,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(31,8);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(31,10);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(31,4);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(32,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(32,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(32,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(32,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(32,1);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(32,1);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(32,9);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(32,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(32,3);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(32,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(33,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(33,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(33,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(33,10);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(33,3);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(33,3);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(33,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(33,4);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(33,6);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(33,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(33,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(34,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(34,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(34,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(34,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(34,6);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(34,9);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(34,3);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(34,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(34,10);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(34,5);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(34,3);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(35,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(35,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(35,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(35,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(35,5);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(35,9);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(35,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(35,8);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(35,10);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(35,4);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(35,1);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(36,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(36,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(36,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(36,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(36,1);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(36,1);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(36,9);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(36,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(36,3);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(36,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(36,6);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(37,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(37,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(37,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(37,10);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(37,3);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(37,3);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(37,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(37,4);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(37,6);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(37,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(37,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(37,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(38,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(38,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(38,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(38,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(38,6);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(38,9);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(38,3);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(38,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(38,10);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(38,5);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(38,3);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(38,8);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(39,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(39,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(39,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(39,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(39,5);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(39,9);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(39,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(39,8);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(39,10);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(39,4);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(39,1);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(39,1);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(40,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(40,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(40,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(40,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(40,1);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(40,1);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(40,9);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(40,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(40,3);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(40,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(40,6);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(40,10);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(41,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(41,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(41,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(41,10);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(41,3);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(41,3);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(41,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(41,4);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(41,6);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(41,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(41,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(41,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(41,7);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(42,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(42,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(42,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(42,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(42,6);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(42,9);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(42,3);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(42,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(42,10);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(42,5);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(42,3);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(42,8);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(42,6);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(43,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(43,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(43,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(43,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(43,5);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(43,9);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(43,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(43,8);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(43,10);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(43,4);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(43,1);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(43,1);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(43,4);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(44,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(44,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(44,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(44,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(44,1);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(44,1);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(44,9);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(44,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(44,3);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(44,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(44,6);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(44,10);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(44,10);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(45,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(45,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(45,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(45,10);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(45,3);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(45,3);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(45,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(45,4);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(45,6);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(45,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(45,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(45,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(45,7);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(45,9);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(46,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(46,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(46,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(46,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(46,6);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(46,9);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(46,3);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(46,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(46,10);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(46,5);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(46,3);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(46,8);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(46,6);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(46,10);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(47,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(47,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(47,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(47,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(47,5);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(47,9);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(47,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(47,8);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(47,10);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(47,4);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(47,1);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(47,1);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(47,4);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(47,9);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(48,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(48,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(48,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(48,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(48,1);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(48,1);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(48,9);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(48,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(48,3);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(48,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(48,6);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(48,10);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(48,10);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(48,8);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(49,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(49,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(49,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(49,10);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(49,3);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(49,3);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(49,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(49,4);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(49,6);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(49,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(49,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(49,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(49,7);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(49,9);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(49,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(50,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(50,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(50,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(50,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(50,6);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(50,9);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(50,3);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(50,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(50,10);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(50,5);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(50,3);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(50,8);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(50,6);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(50,10);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(50,5);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(51,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(51,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(51,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(51,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(51,5);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(51,9);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(51,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(51,8);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(51,10);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(51,4);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(51,1);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(51,1);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(51,4);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(51,9);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(51,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(52,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(52,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(52,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(52,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(52,1);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(52,1);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(52,9);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(52,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(52,3);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(52,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(52,6);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(52,10);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(52,10);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(52,8);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(52,3);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(53,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(53,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(53,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(53,10);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(53,3);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(53,3);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(53,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(53,4);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(53,6);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(53,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(53,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(53,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(53,7);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(53,9);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(53,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(53,9);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(54,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(54,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(54,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(54,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(54,6);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(54,9);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(54,3);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(54,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(54,10);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(54,5);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(54,3);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(54,8);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(54,6);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(54,10);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(54,5);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(54,8);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(55,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(55,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(55,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(55,5);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(55,9);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(55,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(55,8);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(55,10);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(55,4);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(55,1);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(55,1);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(55,4);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(55,9);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(55,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(55,7);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(56,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(56,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(56,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(56,1);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(56,9);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(56,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(56,3);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(56,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(56,6);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(56,10);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(56,10);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(56,8);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(56,3);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(56,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(57,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(57,10);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(57,3);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(57,3);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(57,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(57,4);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(57,6);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(57,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(57,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(57,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(57,7);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(57,9);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(57,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(57,9);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(57,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(58,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(58,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(58,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(58,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(58,6);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(58,9);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(58,3);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(58,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(58,5);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(58,3);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(58,6);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(58,10);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(58,5);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(58,8);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(58,7);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(59,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(59,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(59,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(59,5);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(59,9);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(59,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(59,8);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(59,10);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(59,4);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(59,1);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(59,1);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(59,4);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(59,9);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(59,2);
INSERT INTO turn_cards(turn_id,cards_id) VALUES(59,7);


-- PUNTUACION --
INSERT INTO details(punctuation, game_id, user_id) VALUES(40,1,7);
INSERT INTO details(punctuation, game_id, user_id) VALUES(52,1,8);
INSERT INTO details(punctuation, game_id, user_id) VALUES(52,1,9);
INSERT INTO details(punctuation, game_id, user_id) VALUES(39,1,10);


-- LOGROS --
INSERT INTO achievement(name, description, achievement_type, threshold, badge_image) VALUES ('Inicio', 'Juega LIMIT partida', 'Victories', 1, 'logroJugarGames.png');
INSERT INTO achievement(name, description, achievement_type, threshold, badge_image) VALUES ('Veterano', 'Juega mas de LIMIT partidas', 'Games', 50, 'logroJugarGames.png');
INSERT INTO achievement(name, description, achievement_type, threshold, badge_image) VALUES ('Veterano', 'Juega mas de LIMIT partidas', 'Games', 2, 'logroJugarGames.png');
-- INSERT INTO achievement(name, description, achievement_type, threshold, badge_image) VALUES ('Poco a poco', 'Gana <LIMITE> partida', 'Victories', 1, '/resources/images/grafics/logroVictoria.png');
-- INSERT INTO achievement(name, description, achievement_type, threshold, badge_image) VALUES ('Imparable', 'Gana un total de <LIMITE> partidas', 'Victories', 20, '/resources/images/grafics/logroVictoria.png');
-- INSERT INTO achievement(name, description, achievement_type, threshold, badge_image) VALUES ('Valioso', 'Consigue el set de tesoros distintos mas grande (<LIMITE>)', 'Punctuation', 9, '/resources/images/grafics/logroPuntuacion.png');
-- INSERT INTO achievement(name, description, achievement_type, threshold, badge_image) VALUES ('Reluciente', 'Consigue todos los diamantes (<LIMITE>) en una partida', 'Punctuation', 3, '/resources/images/grafics/logroPuntuacion.png');
-- INSERT INTO achievement(name, description, achievement_type, threshold, badge_image) VALUES ('Duelo', 'Gana <LIMITE> partida por desempate por tener mas doblones que tu rival', 'Punctuation', 1, '/resources/images/grafics/logroPuntuacion.png');
-- INSERT INTO achievement(name, description, achievement_type, threshold, badge_image) VALUES ('Comerciante', 'Contrata a barcos piratas para moverte a otra isla <LIMITE> veces', '', 30, '/resources/images/grafics/logroSaltarIslas.png');
-- INSERT INTO achievement(name, description, achievement_type, threshold, badge_image) VALUES ('Afortunado', 'Obten <LIMITE> seis consecutivos', 'DiceResults', 3, '/resources/images/grafics/logroResultadosDado.png');

INSERT INTO register(acquisition_date, achievement_id, user_id) VALUES ('2022-12-29', 1, 7);
INSERT INTO register(acquisition_date, achievement_id, user_id) VALUES ('2022-12-28', 2, 7);
INSERT INTO register(acquisition_date, achievement_id, user_id) VALUES ('2022-12-28', 2, 8);